//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovars
    {
        public int IdTovar { get; set; }
        public string Article { get; set; }
        public int TovarTitleID { get; set; }
        public string Measurement { get; set; }
        public int Price { get; set; }
        public int SizeMaxDiscount { get; set; }
        public int ManufacturerID { get; set; }
        public int SupplierID { get; set; }
        public int TovarCategoryID { get; set; }
        public int ActualDiscount { get; set; }
        public int QuantityStock { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        public byte[] ImagePhoto { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TovarCategory TovarCategory { get; set; }
        public virtual TovarTitle TovarTitle { get; set; }
    }
}
